### ISSUE TITLE
Oneliner bug: smiley doesn't render

### ISSUE THREAD

**Issue by equin0x80** [arabek/demovibes#11] opened 2017-01-22 20:16 UTC
In the oneliner, type a three-letter message like ABC. Then go to Smileys box and choose the pink pony. Then go to Smileys box and choose the heart. When you send the message, ABC and pony appear, but the heart shows up as text <3 instead of a picture.

**Comment by arabek** [comment] 2017-04-03 06:47
Not a bug, it's a feature to prevent smiley spamming.
#wontfix

**Closed by arabek** 2017-04-03 06:47 UTC
